spring.application.name=quest-llm

server.port=8081

# LM Studio Configuration
spring.ai.openai.chat.base-url=http://localhost:1234
spring.ai.openai.api-key=lm-studio
spring.ai.openai.chat.options.model=dolphin3-8k

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/notes
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.threads.virtual.enabled=true
# This tells Jackson to use the primitive default (like 0 for long) instead of crashing on null
#spring.jackson.deserialization.fail-on-null-for-primitives=false

spring.kafka.bootstrap-servers=localhost:9092
# Deserializing bytes back into JSON/Objects
spring.kafka.consumer.group-id=quest-embedding-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
# Trusted packages is required for JsonDeserializer to prevent security exploits
spring.kafka.consumer.properties.spring.json.trusted.packages=*